# Generated by Django 5.0.2 on 2024-03-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Register_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_name", models.CharField(max_length=50)),
                ("c_model", models.CharField(max_length=50)),
                ("c_ac", models.CharField(max_length=10)),
                ("c_avg", models.CharField(max_length=50)),
                ("file", models.FileField(default="0", upload_to="media/photo")),
            ],
        ),
    ]
