# Generated by Django 5.0.2 on 2024-03-22 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CRMS", "0003_demo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="demo",
        ),
    ]
