# Generated by Django 5.0.2 on 2024-03-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CRMS", "0006_user_registration_model_password_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="user_registration_model",
        ),
    ]
