# Generated by Django 5.0.2 on 2024-03-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRMS", "0008_user_registration_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="driver_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first", models.CharField(max_length=20)),
                ("last", models.CharField(max_length=20)),
                ("dob", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=20)),
                ("aadhar", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first", models.CharField(max_length=20)),
                ("last", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=100)),
                ("aadhar", models.CharField(max_length=20)),
                ("office", models.CharField(max_length=100)),
                ("time", models.CharField(max_length=20)),
                ("driver", models.CharField(default="0", max_length=20)),
                ("from_date", models.CharField(max_length=20)),
                ("to_date", models.CharField(max_length=20)),
                ("days", models.CharField(max_length=20)),
                ("passengers", models.CharField(max_length=20)),
                ("payment_type", models.CharField(max_length=30)),
                ("bill", models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name="user_registration_model",
        ),
    ]
