# Generated by Django 5.0.2 on 2024-03-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRMS", "0009_driver_model_order_delete_user_registration_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="c_am",
            field=models.CharField(default="0", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="c_model",
            field=models.CharField(default="0", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="c_name",
            field=models.CharField(default="0", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="c_price",
            field=models.CharField(default="0", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="d_bill",
            field=models.CharField(default="0", max_length=30),
        ),
        migrations.AlterField(
            model_name="order",
            name="aadhar",
            field=models.CharField(default="0", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="bill",
            field=models.CharField(default="0", max_length=30),
        ),
        migrations.AlterField(
            model_name="order",
            name="days",
            field=models.CharField(default="0", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.CharField(default="0", max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="first",
            field=models.CharField(default="0", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="from_date",
            field=models.CharField(default="0", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="last",
            field=models.CharField(default="0", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="office",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="passengers",
            field=models.CharField(default="0", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_type",
            field=models.CharField(default="0", max_length=30),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(default="0", max_length=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="time",
            field=models.TimeField(default="0", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="to_date",
            field=models.CharField(default="0", max_length=20),
        ),
    ]
