# Generated by Django 5.0.2 on 2024-03-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CRMS", "0010_order_c_am_order_c_model_order_c_name_order_c_price_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="order",
            new_name="order_model",
        ),
    ]
