# Generated by Django 5.0.2 on 2024-03-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRMS", "0011_rename_order_order_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order_model",
            name="time",
            field=models.CharField(default="0", max_length=20),
        ),
    ]
